# Generated by Django 6.0.2 on 2026-03-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=50, unique=True, verbose_name='Número de Serie')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('procesador', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=20, verbose_name='Memoria RAM (GB)')),
                ('estado', models.CharField(choices=[('Activo', 'Activo - En uso'), ('Mantenimiento', 'En Mantenimiento'), ('Baja', 'Dado de Baja')], default='Activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
        ),
    ]
