# Generated by Django 6.0.2 on 2026-03-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='disco_duro',
            field=models.CharField(default='No especificado', max_length=50, verbose_name='Almacenamiento (Disco Duro)'),
        ),
    ]
