# Generated by Django 6.0.2 on 2026-03-04 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_equipo_disco_duro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del Mantenimiento')),
                ('tipo', models.CharField(choices=[('Preventivo', 'Preventivo (Limpieza, actualización)'), ('Correctivo', 'Correctivo (Reparación de falla)')], default='Preventivo', max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripción del trabajo realizado')),
                ('tecnico', models.CharField(max_length=100, verbose_name='Técnico que realizó el trabajo')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo', verbose_name='Equipo')),
            ],
        ),
    ]
