# Generated by Django 6.0.2 on 2026-03-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='estado_mantenimiento',
            field=models.CharField(choices=[('Pendiente', 'Pendiente por revisar'), ('En curso', 'Trabajando en el equipo'), ('Terminado', 'Mantenimiento finalizado')], default='Pendiente', max_length=20, verbose_name='Estado del Mantenimiento'),
        ),
    ]
