# Generated by Django 6.0.2 on 2026-03-04 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_mantenimiento_estado_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Reporte')),
                ('solicitante', models.CharField(max_length=100, verbose_name='¿Quién reporta? (Ej. Alumno/Maestro)')),
                ('descripcion_falla', models.TextField(verbose_name='Descripción del problema')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de revisión'), ('Atendido', 'Mantenimiento realizado')], default='Pendiente', max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo', verbose_name='Equipo que falla')),
            ],
        ),
    ]
