# Generated by Django 6.0.2 on 2026-03-04 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_reportefalla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Edificio/Área')),
            ],
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='reporte_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.reportefalla', verbose_name='Reporte Asociado'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción del trabajo'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tecnico',
            field=models.CharField(max_length=100, verbose_name='Técnico (CC)'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(choices=[('Preventivo', 'Preventivo (Limpieza)'), ('Correctivo', 'Correctivo (Falla)')], default='Preventivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportefalla',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de revisión'), ('En Revision', 'En revisión por CC'), ('Finalizado', 'Mantenimiento finalizado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportefalla',
            name='solicitante',
            field=models.CharField(max_length=100, verbose_name='¿Quién reporta?'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='edificio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.edificio', verbose_name='Ubicación (Edificio)'),
        ),
    ]
