# Generated by Django 6.0.2 on 2026-05-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_edificio_mantenimiento_reporte_vinculado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='sistema_operativo',
            field=models.CharField(choices=[('Windows 10', 'Windows 10'), ('Windows 11', 'Windows 11'), ('Linux', 'Linux / Ubuntu'), ('MacOS', 'MacOS / Apple'), ('Otro', 'Otro OS')], default='Windows 10', max_length=20, verbose_name='Sistema Operativo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='disco_duro',
            field=models.CharField(default='No especificado', max_length=50, verbose_name='Almacenamiento'),
        ),
    ]
