# Generated by Django 6.0.2 on 2026-05-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_equipo_sistema_operativo_alter_equipo_disco_duro'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefalla',
            name='folio',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Folio del Reporte'),
        ),
    ]
